### ISSUE TITLE
Can't synchronize two nexus repositories

### ISSUE THREAD

**Issue by d-malko** [regclient/regclient#125]
At the first thank you for your work! 
Your program helps a lot

Now, I am trying to migrate and synchronize two nexus registries from older to newer.
All images from the docker hosted repository with all tags need to be synchronized to the newer registry.

regsync.yml
```
version: 1
creds:
  - registry:  nexusprd.company.com
    user: "admin"
    pass: "1234"
  - registry: localhost:8091
    user: "admin"
    pass: "1234"
    tls: disabled
defaults:
  interval: 60m
sync:
  - source: localhost:8091
    target: nexusprd.company.com
    type: registry
```

### Steps to reproduce

To simplify things. I am running regsync on older nexus directly.

![image](https://user-images.githubusercontent.com/26520297/146452326-de722c2e-f589-4731-9fe3-c99d0c1afba0.png)

```
./regsync -c  regsync.yml check -v debug
```
```
DEBU[2021-12-16T16:26:19-05:00] Configuring parallel settings                 concurrent=1
DEBU[2021-12-16T16:26:19-05:00] Loading host config                           api= blobChunk=0 blobMax=0 hostname= mirrors="[]" name=nexusprd.company.com pathPrefix= tls= user=admin
DEBU[2021-12-16T16:26:19-05:00] Loading host config                           api= blobChunk=0 blobMax=0 hostname= mirrors="[]" name="localhost:8091" pathPrefix= tls=disabled user=admin
DEBU[2021-12-16T16:26:19-05:00] regclient initialized
DEBU[2021-12-16T16:26:19-05:00] Sending request                               method=GET url="http://localhost:8091/v2/_catalog" withAuth=false
DEBU[2021-12-16T16:26:19-05:00] Auth request parsed                           challenge="[{basic map[realm:Sonatype Nexus Repository Manager]}]"
DEBU[2021-12-16T16:26:19-05:00] Sending request                               method=GET url="http://localhost:8091/v2/_catalog" withAuth=true
DEBU[2021-12-16T16:26:19-05:00] Sending request                               method=GET url="http://localhost:8091/v2/action-orchastrator/tags/list" withAuth=true
DEBU[2021-12-16T16:26:19-05:00] Sending request                               method=HEAD url="http://localhost:8091/v2/action-orchastrator/manifests/1.1" withAuth=true
DEBU[2021-12-16T16:26:19-05:00] Not found                                     Status="404 Not Found" URL="http://localhost:8091/v2/action-orchastrator/manifests/1.1"
ERRO[2021-12-16T16:26:19-05:00] Failed to lookup source manifest              error="Failed to request manifest head localhost:8091/action-orchastrator:1.1: Not found [http 404]" source="localhost:8091/action-orchastrator:1.1"
ERRO[2021-12-16T16:26:19-05:00] Failed to sync                                error="Failed to request manifest head localhost:8091/action-orchastrator:1.1: Not found [http 404]" source="localhost:8091/action-orchastrator:1.1" target="nexusprd.company.com/action-orchastrator:1.1"
DEBU[2021-12-16T16:26:19-05:00] Sending request                               method=HEAD url="http://localhost:8091/v2/action-orchastrator/manifests/1.2" withAuth=true
DEBU[2021-12-16T16:26:19-05:00] Not found                                     Status="404 Not Found" URL="http://localhost:8091/v2/action-orchastrator/manifests/1.2"
ERRO[2021-12-16T16:26:19-05:00] Failed to lookup source manifest              error="Failed to request manifest head localhost:8091/action-orchastrator:1.2: Not found [http 404]" source="localhost:8091/action-orchastrator:1.2"
ERRO[2021-12-16T16:26:19-05:00] Failed to sync                                error="Failed to request manifest head localhost:8091/action-orchastrator:1.2: Not found [http 404]" source="localhost:8091/action-orchastrator:1.2" target="nexusprd.company.com/action-orchastrator:1.2"
...
```

### Version

```
regsync version
{
  "VCSRef": "0cb9b4c8bc5394be47432b3c884ff7933d40d0b8",
  "VCSTag": "v0.3.9"
}

```

### Environment

- Running as binary or container:
  I tried both
- Host platform:
   redhat 7 and redhat 8.4
- Registry description:
    Source  Nexus 3.12.1-01
    Destination: 3.34.0-01

I don't know is a programmatic issue or maybe you can describe this process in documentation. I dig a lot, but I can't understand what the issue is.

**Comment by sudo-bmitch** [comment]
I suspect you're hitting this issue with older versions of Nexus not supporting head requests: https://issues.sonatype.org/plugins/servlet/mobile#issue/NEXUS-12684

Most all of the code favors those head requests because of how Docker Hub excludes them from rate limit counts. There may be some ways to handle your use case by adding an option to the regsync config. I'll have a look at that over the next few weeks.

**Comment by sudo-bmitch** [comment]
The close on this issue was automatic, but I'd like to hear back if that change solved your issue. Try changing the image to `regclient/regctl:edge` and running with the following config:

```yaml
version: 1
creds:
  - registry:  nexusprd.company.com
    user: "admin"
    pass: "1234"
  - registry: localhost:8091
    user: "admin"
    pass: "1234"
    tls: disabled
    apiOpts:
      disableHead: "true"
defaults:
  interval: 60m
sync:
  - source: localhost:8091
    target: nexusprd.company.com
    type: registry
```

If that's not working for you, we can re-open this.
