### ISSUE TITLE
[Feature] Allow for setting a default target repository prefix

### ISSUE THREAD

**Issue by kirooshu** [regclient/regclient#204]
### Current Behavior

Right now, we need to repeat the `target` for a lot of repos we sync from DockerHub:

```
sync:
  - source: alpine
    target: '{{ env "ECR" }}/hub/alpine'
    type: repository
    tags:
      allow:
        - "latest"
        - "edge"
        - "3.1\\d+"

  - source: datadog/agent
    target: '{{ env "ECR" }}/hub/datadog/agent'
    type: repository
    tags:
      allow:
        - "latest"
        - "7.\\d+.\\d+"
```

### Expected Behavior

Be able to avoid copy and paste that can cause human error.

### Example Solution

```
defaults:
  target_prefix: '{{ env "ECR" }}/hub'
sync:
  - source: alpine
    type: repository
    tags:
      allow:
        - "latest"
        - "edge"
        - "3.1\\d+"

  - source: datadog/agent
    type: repository
    tags:
      allow:
        - "latest"
        - "7.\\d+.\\d+"
```

**Comment by kirooshu** [comment]
Btw, we are switching over from https://github.com/seatgeek/docker-mirror and so naturally some of these feature requests are inspire by it. Also, thank you so much for a great and simple tool like `reg*` :)

**Comment by sudo-bmitch** [comment]
Interesting, I hadn't seen their project, thanks for sharing.

I'm thinking over a few different options for how this could be solved. Regardless of how, it's certainly doable.

Until then, one setting that may help is `pathPrefix` that forces a path on all repos for that registry entry, e.g.

```yaml
creds:
  - registry: example.ecr.aws
    pathPrefix: "hub"
sync:
  - source: alpine
    target: 'example.ecr.aws/alpine'
    type: repository
    tags:
      allow:
        - "latest"
        - "edge"
        - "3.1\\d+"

  - source: datadog/agent
    target: 'example.ecr.aws/datadog/agent'
    type: repository
    tags:
      allow:
        - "latest"
        - "7.\\d+.\\d+"
```

You can also set the hostname with something like:

```yaml
creds:
  - registry: hub.mirror
    hostname: example.ecr.aws
    pathPrefix: "/hub"
sync:
  - source: alpine
    target: 'hub.mirror/alpine'
    type: repository
    tags:
      allow:
        - "latest"
        - "edge"
        - "3.1\\d+"
```

But that will cause issues with credential helpers if you're using them.
