### ISSUE TITLE
[Question] How to list paginated repositories from Lua-script?

### ISSUE THREAD

**Issue by mpashkov** [regclient/regclient#329]
### Question

I have the following Lua-script.
```
version: 1
defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 1
  interval: 60m
  backup: "bkup-{{.Ref.Tag}}"
scripts:
  - name: Delete old versions
    script: |
      sourceRegistry = "localhost"

      log("start cleaning:"..sourceRegistry)

      repos = repo.ls(sourceRegistry)

      for i, repository in ipairs(repos) do
        print(repository)
      end
```

Due to pagenation command `repo.ls(hostname)` returns only the first 100 of repositories. I want to get all repositories. At the same time, paginating on Docker Regestry API ( `curl regestryHost/v2/_catalog?n=1000`) or regbot `./regctl repo ls regestryHost --limit 1000` works well.

Pleaese, may you help me find out how to configure this parameter (maximum number of returned repositories) in Lua-script? Maybe, it is not possilble for a while.

### Version

Used docker-image version: `regclient/regbot@sha256:7c83b5b493d696158dd4e34daa00a2a7423937ea20a37b6b7081802803fe28ca`

### Environment

The script is run it like in examples of [Docker Hub](https://hub.docker.com/r/regclient/regbot).

**Comment by sudo-bmitch** [comment]
Hi @mpashkov it's not currently possible, but shouldn't be hard to add an options parameter to that Lua interface. Adding this to my queue.

**Comment by sudo-bmitch** [comment]
This should be fixed in the latest `regclient/regbot:edge` build using the following:

```yaml
version: 1
defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 1
  interval: 60m
  backup: "bkup-{{.Ref.Tag}}"
scripts:
  - name: Delete old versions
    script: |
      sourceRegistry = "localhost"

      log("start cleaning:"..sourceRegistry)

      repos = repo.ls(sourceRegistry, {limit = 1000})

      for i, repository in ipairs(repos) do
        print(repository)
      end
```

Let me know if you run into any trouble with it, and thanks for the request!
