### ISSUE TITLE
How can I use a different docker logins for source and destination Sync . Any example will be helpful

### ISSUE THREAD

**Issue by balu-ce** [regclient/regclient#397]
`version: 1
defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
  interval: 60m
sync:
  - source: openpolicyagent/gatekeeper
    target: XXXX.dkr.ecr.us-east-1.amazonaws.com/security/XXXX:XXX
    type: repository
    tags:
      allow:
      - "XXX"`

**Comment by sudo-bmitch** [comment]
Hi @balu-ce. If docker is logged into multiple registries, and you are running regsync as a binary rather than a container, it will see those logins and use them. If you are running as a container, you'll need to ensure the volume mounts the docker config file (`$HOME/.docker/config.json`) along with any details and commands needed by credential helpers if those are used. If you aren't logged in with the docker command line, the `creds` section is used to define logins for each registry, and an example of that is included in the docs: https://github.com/regclient/regclient/blob/main/docs/regsync.md#configuration-file

Each registry can have its own configuration, e..g.:

```yaml
creds:
  - registry: localhost:5000
    tls: disabled
  - registry: docker.io
    user: "{{env \"HUB_USER\"}}"
    pass: "{{file \"/var/run/secrets/hub_token\"}}"
  - registry: registry.example.com
    user: "bot"
    pass: "password123"
```
