### ISSUE TITLE
[Issue] regsync limits syncs to 100 repositories in ACR

### ISSUE THREAD

**Issue by Ottovsky** [regclient/regclient#404]
### Current Behavior

Our organization uses Azure Container Registry (ACR) to store our docker images. To keep our images in sync across multiple registries, we've been using regsync. However, we've noticed that some images aren't getting synced. After investigating the issue, we discovered that regsync only processes the first batch of repositories returned by https://contoso.azurecr.io/v2/_catalog, which is limited to 100 entries by default. Therefore, the synchronization process stops after 100 repositories have been synced.

### Expected Behavior

Sync all (>100) repositories  between ACRs.

### Steps To Reproduce
1. Ensure that there are more than 100 repositories in the first Azure Container Registry (contoso1).
2. Use the following configuration in config.yaml:
```yaml
version: 1
creds:
  - registry: contoso1.azurecr.io
    repoAuth: true
  - registry: contoso2.azurecr.io
    repoAuth: true
sync:
  - source: contoso1.azurecr.io
    target: contoso2.azurecr.io
    type: registry
```    
3. Run `regsync once -v debug -c config.yaml`.
4. Observe that not all repositories are synced between the two registries.

### Version

```text
VCSRef:     f43ada160d953317c51e7d9170afa2a316f4b9be
VCSCommit:  f43ada160d953317c51e7d9170afa2a316f4b9be
VCSState:   clean
VCSDate:    2023-02-26T02:43:41Z
Platform:   linux/amd64
GoVer:      go1.20.1
GoCompiler: gc

```

### Environment

- Running as binary or container:  binary 
- Host platform:  Linux x86
- Registry description: Azure ACR
