### ISSUE TITLE
[Feature] support env vars for everything

### ISSUE THREAD

**Issue by runningman84** [regclient/regclient#520]
### Current Behavior

My config looks like this:
`````
version: 1
creds:
- registry: "{{env \"SRC_REGISTRY\"}}"
  user: "{{env \"SRC_USER\"}}"
  pass: "{{env \"SRC_PASS\"}}"
- registry: "{{env \"DST_REGISTRY\"}}"
  user: "{{env \"DST_USER\"}}"
  pass: "{{env \"DST_PASS\"}}"

defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
- source: "{{env \"SRC_REGISTRY\"}}/{{env \"SRC_REPO\"}}"
  target: "{{env \"DST_REGISTRY\"}}/{{env \"DST_REPO\"}}"
  type: repository

`````

My env vars look like this:
``````
+ SRC_USER=***
+ SRC_PASS=***
+ SRC_REGISTRY=docker.io
+ SRC_REPO=library/alpine
+ DST_USER=***
+ DST_PASS=***
+ DST_REPO=arvatoaws-labs/alpine
+ DST_REGISTRY=ghcr.io
+ CONFIG=config/generic.yaml
``````

But I get this error:
``````
time="2023-08-24T13:19:05Z" level=error msg="Failed parsing source" error="invalid reference \"/\"" source=/
invalid reference "/"
``````

It looks like vars are not supported in the source or target section.

### Expected Behavior

support env vars everywhere in the configfile.

### Version

```text
0.5.1
```

### Environment

- Running as binary or container: binary
- Host platform: github actions
- Registry description: docker hub / github packages
