### ISSUE TITLE
[Feature][regsync] Support for nested repositories type

### ISSUE THREAD

**Issue by t3mi** [regclient/regclient#533]
### Current Behavior
Its not possible to use single step for `regsync` to copy all nested repositories behind path/folder.

### Expected Behavior
Please add new `type` value in sync step which will be used to copy all nested repositories with images.

### Example Solution
The following example means that all the nested repositories with all available images behind path `mcr.microsoft.com/windows` will be copied to private ACR registry.
```yaml
...
sync:
  - source: 'mcr.microsoft.com/windows'
    target: 'registry.azurecr.io/windows'
    type: path
...
```

**Comment by sudo-bmitch** [comment]
I believe #538 will support your use case. The implementation would look like:

```yaml
sync:
  - source: mcr.microsoft.com
    target: registry.azurecr.io
    type: registry
    repos:
      allow:
        - 'windows\/.*'
```
