### ISSUE TITLE
[Question] Using artifact put in a github action

### ISSUE THREAD

**Issue by KevinDMack** [regclient/regclient#756]
### Question

So I'm trying to use regctl in a github action, and I'm running into a problem with using the docker login and then using the GITHUB_TOKEN.  No matter what I do I continue to get an access denied for trying to perform the artifact put.  

For context and code sample, I have the following structure:
.
├── README.md
├── hostsvc-test
│   └── test-file.txt

I am trying to make a github action that will publish this text file as an OCI artifact to github packages.  Below is the yaml workflow I am using:
```yaml
name: hostsvc-test

on:
  push:
    branches: [ main ]
    paths: 
        - 'hostsvc-test/*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Install RegCtl
      run: |
        VER_REGCTL=v0.5.7
        echo "Installing regctl - version ${VER_REGCTL}..."
        curl -L https://github.com/regclient/regclient/releases/download/${VER_REGCTL}/regctl-linux-amd64 >regctl
        sudo mv regctl /usr/local/bin/
        sudo chmod 755 /usr/local/bin/regctl
        rm -rf regctl
        echo "Getting Version Information"
        regctl version

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push file with regctl
      run: |
        echo "Setting up manifest"
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        regctl index create ghcr.io/${REPO_LOWER}/test:latest \
          --media-type application/vnd.docker.distribution.manifest.list.v2+json

        echo "Pushing file to registry..."
        regctl artifact put --subject ghcr.io/${REPO_LOWER}/test:latest \
                            --file ./hostsvc-test/test-file.txt \
                            --strip-dirs \
                            --artifact-type application/bnd.test.amd64.buildartifact \
                            --file-media-type application/vnd.test.amd64.buildartifact \
                            --index ghcr.io/${REPO_LOWER}/test:latest
```
But whenver I run this, I get the following:

```
failed to put manifest ghcr.io/kevindmack/action-playground/kemack-test:latest: request failed: unauthorized [http 403]: {"errors":[{"code":"DENIED","message":"permission_denied: write_package"}]}
```

Now what's confusing to me, is that I've given the GITHUB_TOKEN write permissions on the package, and for reference this repo is a private personal repo I'm using for experimenting with github actions.   And I am  trying to have the workflow push to the package on the exact same repo as the workflow file.  Is there something I'm missing with authentication for regctl?  

### Version

```text
Getting Version Information
VCSTag:     v0.5.7
VCSRef:     832109d4e9ef96982c4a4a8614b276b752509e5b
VCSCommit:  832109d4e9ef96982c4a4a8614b276b752509e5b
VCSState:   clean
VCSDate:    20[24](https://github.com/KevinDMack/action-playground/actions/runs/9320392072/job/25657102504#step:7:25)-02-06T21:25:52Z
Platform:   linux/amd64
GoVer:      go1.21.6
GoCompiler: gc
```
