### ISSUE TITLE
[Feature] Ref Parsing & Manipulation Functionality

### ISSUE THREAD

**Issue by paul-cureton** [regclient/regclient#760]
It is often needed to process the data embedded in a reference.  Please consider including functionality to work with references directly.  Here are a few examples:

### regctl
Parse a reference into structured data that other tools or code can use:
```
# Splitting across lines for readability, probably better to actually print on one line
$ regctl reference inspect busybox
> {
  "registry": "docker.io",
  "repository": "library/busybox",
  "tag": "latest",
  "digest": null,
  "name": "library/busybox:latest"
}

$ regctl reference inspect --verbose http://my.test:5000/a/b/c@sha512:<...val>
> {
  "scheme": "http",
  "insecure": true,
  "host": "my.test",
  "port": 5000,
  "registry": "my.test:5000",
  "repositoryParts": ["a", "b", "c"],
  "repository": "a/b/c"
  "tag": "latest"
  "digest": "sha512:<...val>",
  "algorithm": "sha512",
  "encode": "<...val>",
  "tag": null,
  "nameSuffix": "@sha512:<...val>",
  "name": "a/b/c@sha512:<...val>"
}
```

Format references to normalize or manipulate them:
```
$ regctl reference normalize busybox
> docker.io/library/busybox:latest

$ regctl reference normalize busybox --format "myregistry.test/{{ .name }}"
> myregistry.test/library/busybox:latest

$ source="myregistry.test/dev/team/service:latest"
$ format='{{ .registry }}/qa/{{ slice .repositoryParts 1 | join "/" }}{{ .nameSuffix }}'
$ target=$(regctl reference normalize "$source" --format "$format")
$ regctl image copy "$source" "$target"
```

### regsync
More Go templates for `regsync`:
```yaml
sync:
  # Simple copy
  - source: alpine
    target: "myregistry.test/{{ .source.name }}"
    type: image
  # Their prod is our dev
  - source: "vendor.test"
    target: "myregistry.test/{{ .source.repository }}:dev"
    tags:
      allow: ["prod"]
    type: registry
```

### regbot
Expanded lua `ref` for `regbot`:
```yaml
scripts:
  - name: a
    script: |
     source = reference.new("debian")
     target = reference.new("myregistry.test/customNamespace/" .. source.name)
     image.copy(source, target)
  - name: b
    script: |
      source = reference.new("debian")
      if source.digest == nil then
        -- Or something like this; unsure if this functionality exists already
        source.digest = tag.resolveDigest(source)
      end
      if source.algorithm ~= "sha512" then
        log("Not quantum resistant")
      else
        target = reference.new("myregistr.test/customNamespace" .. source.repository .. "@" .. source.digest)
        image.copy(source, target)
      done
```

Thanks 🙂
