### ISSUE TITLE
[Issue] Unable to use regsync with self-hosted quay syncing whole registry

### ISSUE THREAD

**Issue by jonas-budde** [regclient/regclient#789]
### Current Behavior
I don't get an output while trying to sync a self hosted quay registry to an Azure Container Registry. The same setup worked with an ACR to ACR sync.

The Sync between self-hosted quay and ACR currently only works with type: image and repository, but it would me very convenient to just define a registry and not every single repository.

My provided quay user has access to self-hosted-quay.company.com/xyz and everything below that

Am I doing something wrong?

### Expected Behavior
I should be able to define my config like this:

```
version: 1
  sync:
    - source: self-hosted-quay.company.com
      target: my-acr.azurecr.io
      type: registry
      interval: 1m
```

and it should sync the whole available registry of this user to my specified target registry.
As im running regsync as a kubernetes container with the server option, the docker config is used from the /home/appuser path.

### Steps To Reproduce

Use the config above.

### Version

Docker Container Version: 0.7.0

### Environment

- Kubernetes (Azure Linux Nodes)
- Source Registry: self-hosted quay
- Target Registry: ACR

### additional infos

quay version: https://github.com/quay/quay/releases Quay v3.11.0
