### ISSUE TITLE
[Feature] support multiple user-defined platforms with regsync

### ISSUE THREAD

**Issue by jtackaberry** [regclient/regclient#884]
### Current Behavior

regsync today either copies all platforms from a multi-platform image, or a single specified platform.  Those of us interested in only, say, `linux/amd64` and `linux/arm64` would end up unnecessarily copying and storing data for unused platforms.

### Expected Behavior

I would like to be able to specify arbitrarily many platforms to copy, rather than all or one.

If any of the listed platforms are not available in the source image, this isn't considered an error and instead the missing platform is quietly skipped.

If the source later includes any missing platform relative to the initial sync, then the newly added platforms are synced.

### Example Solution

This could be configured by allowing the existing `platform` to be a comma-delimited list of platforms, such as:

```yaml
sync:
  - source: docker.io/some/image
    target: myreg.example.com/some/image
    type: repository
    platform: linux/amd64,linux/arm64
```

Or introduce a new `platforms` field that accepts a list:

```yaml
sync:
  - source: docker.io/some/image
    target: myreg.example.com/some/image
    type: repository
    platforms:
      - linux/amd64
      - linux/arm64
```

In either case, the idea is that only those two platforms would be synced from the source.

### Version

```text
VCSTag:     v0.7.2
VCSRef:     6b1f7bd9a3b2972605f04a534143f7fed522b680
VCSCommit:  6b1f7bd9a3b2972605f04a534143f7fed522b680
VCSState:   clean
VCSDate:    2024-11-04T14:37:25Z
Platform:   linux/amd64
GoVer:      go1.23.2
GoCompiler: gc
```

### Environment

- Running as binary or container: binary
- Host platform: Linux
- Registry description: Source is various, target is ECR
