### ISSUE TITLE
[Issue] v0.8.1 can't copy images to ACR

### ISSUE THREAD

**Issue by ba-work** [regclient/regclient#907]
### Current Behavior

We have CI that mirrors images to an ACR using regctl; the reality is _slightly_ more complex than this, but this the relevant gist of it:
```yaml
# ...
    - name: Login to ACR
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ secrets.ACR }}.azurecr.io
        username: 00000000-0000-0000-0000-000000000000
        password: ${{ secrets.accessToken }}

    - name: Install regctl
      run: |
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > /usr/local/bin/regctl
        chmod a+x /usr/local/bin/regctl

   - name: Copy images
      run: |
        regctl image copy \
          ${{ matrix.image.registry }}/${{ matrix.image.repository }}:${{ matrix.image.tag }} \
          ${{ secrets.ACR }}.azurecr.io/${{ matrix.image.repository }}:${{ matrix.image.tag }}
# ...
```
Starting with v0.8.1 this no longer works, and it logs stuff like this:
```
time=2025-02-12T13:45:57.966Z level=WARN msg="Failed to push blob" src=docker.io/bats/bats@sha256:307029d0feff7a342ccf3be7d775b0209e581300a1dc894dbdcaa972d9e00aef tgt=***.azurecr.io/cache/bats/bats@sha256:307029d0feff7a342ccf3be7d775b0209e581300a1dc894dbdcaa972d9e00aef err="failed to send blob post, ref ***.azurecr.io/cache/bats/bats@sha256:307029d0feff7a342ccf3be7d775b0209e581300a1dc894dbdcaa972d9e00aef: unauthorized"
```
To workaround, I had to hardcode the `Install regctl` step to use **v0.8.0**. 
I suspect its related to #894 but I'm not sure how `docker/login-action` actually populates `.docker/config.json`

### Expected Behavior

The images are copied via `regctl` using appropriate authentication.

### Steps To Reproduce

1. auth to an ACR with plain `docker login`
2. try to `regctl image copy ...`

### Version

```text
VCSTag:     v0.8.1
VCSRef:     80af8a3ace6d8fb26bc1fa8e4c4a7ca3a9e877f2
VCSCommit:  80af8a3ace6d8fb26bc1fa8e4c4a7ca3a9e877f2
VCSState:   clean
VCSDate:    2025-02-11T21:41:05Z
Platform:   linux/amd64
GoVer:      go1.23.6
GoCompiler: gc
```

### Environment

- Running as binary or container: binary
- Host platform: Linux
- Registry description: image copying from docker.io to an ACR

### Anything else

I think #894 since that looks like the only change to something auth related

**Comment by sudo-bmitch** [comment]
Please provide the following:

```shell
cat .docker/config.json # censor hostnames and credentials if needed
regctl registry config # censor hostnames if needed
regctl image copy -v debug ... # censor hostnames if needed
```

**Comment by sudo-bmitch** [comment]
I see where this went wrong. It's the identity token in the login instead of a password. The logic moved from POST to GET for most login requests, but still has the POST for refresh tokens. I need to also run a POST when there's an identity token.

@ba-work I'd like to double check something with you out-of-band ASAP. Please ping me at git@bmitch.net or the CNCF, OCI, OpenSSF slacks.

**Comment by sudo-bmitch** [comment]
I think this is resolved by #908. If you want the easy button for testing that, there's a GitHub action for regclient that installs it based on the passed version: https://github.com/regclient/actions:

```yaml
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
        with:
          release: 'main'
```

If that works, I'll cut a new release by the end of the week.
