### ISSUE TITLE
[Issue] regsync file access to regsync.yml not working in docker compose

### ISSUE THREAD

**Issue by DarkSpir** [regclient/regclient#938]
### Current Behavior

I want to run regsync as a docker container with the server command. While it works fine on command line, the container fails to start when set up via docker compose:

regsync.yml:
```
x-sched-qual: &sched-qual "00 20 14 * *"
x-sched-prod: &sched-prod "00 20 28 * *"
version: 1
creds:
  - registry: prod-registry:5000
    tls: disabled
  - registry: qual-registry:5000
    tls: disabled
defaults:
  parallel: 1
  interval: 1440m
sync:
  # Basic
  - source: traefik:latest
    target: qual-registry:5000/library/traefik:latest
    type: image
    schedule: *sched-qual
  # Keycloak Stack
  - source: keycloak/keycloak:latest
    target: qual-registry:5000/keycloak/keycloak:latest
    type: image
    schedule: *sched-qual
  # Netbox stack
  - source: ghcr.io/netbox-community/netbox:latest
    target: qual-registry:5000/netbox-community/netbox:latest
    type: image
    schedule: *sched-qual
  - source: postgres:17-alpine
    target: qual-registry:5000/library/postgres:17-alpine
    type: image
    schedule: *sched-qual
  - source: valkey/valkey:8.0-alpine
    target: qual-registry:5000/valkey/valkey:8.0-alpine
    type: image
    schedule: *sched-qual
  # Sync: Qual to Prod
  - source: qual-registry:5000
    target: prod-registry:5000
    type: registry
    schedule: *sched-prod
```

docker-compose.yml:
```
---
networks:
  frontend:
    external: true

services:
  regsync:
    image: ghcr.io/regclient/regsync:latest
    command:
      - "-c /home/appuser/regsync.yml"
      - "server"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - frontend
    volumes:
      - /etc/pki/trust/anchors/WebProxyCA.crt:/etc/ssl/certs/WebProxyCA.crt:ro
      - ./regsync.yml:/home/appuser/regsync.yml:ro
...
```

When I start the stack:
```
 # docker compose up
[+] Building 0.0s (0/0)                                                                                                                                                                             docker:default
[+] Running 0/0
[+] Running 1/1egsync-regsync-1  Creating                                                                                                                                                                      0.1s ג Container regsync-regsync-1  Created                                                                                                                                                                       0.1s
Attaching to regsync-regsync-1
regsync-regsync-1  | open  /home/appuser/regsync.yml: no such file or directory
regsync-regsync-1 exited with code 0
```

It cannot open regsync.yml.

### Expected Behavior

When I create the container using cli commands, it just works:
```
docker container run -i --rm --net frontend -v "./regsync.yml:/home/appuser/regsync.yml:ro" -v "/etc/pki/trust/anchors/WebProxyCA.crt:/etc/ssl/certs/WebProxyCA.crt:ro" ghcr.io/regclient/regsync:latest -c /home/appuser/regsync.yml server
```
regsync.yml gets loaded, regsync starts as server and when the schedule triggers, it syncs the images.

### Steps To Reproduce

Put the `docker-compose.yml` and `regsync.yml` files from the description above in one directory, create a bridged network named `frontend` and run `docker compose up`.

### Version

```text
# docker inspect ghcr.io/regclient/regsync:latest
[
    {
        "Id": "sha256:8047a752d376dc90d6f0ae007cb5fc52bc02f3c5673a845bc22feecf52fd1aff",
        "RepoTags": [
            "ghcr.io/regclient/regsync:latest"
        ],
        "RepoDigests": [
            "ghcr.io/regclient/regsync@sha256:b3f8b2b8a0a61a96b6d1ed3c6f2ef361819d8508de32ddccb3e89f6500c2a685"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2025-02-14T14:58:53Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "appuser",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/regsync"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "",
                "org.opencontainers.image.authors": "regclient contributors",
                "org.opencontainers.image.created": "2025-02-14T14:58:53Z",
                "org.opencontainers.image.description": "regclient/regsync utility for mirroring registry content (scratch)",
                "org.opencontainers.image.documentation": "https://github.com/regclient/regclient",
                "org.opencontainers.image.licenses": "Apache 2.0",
                "org.opencontainers.image.revision": "e7e5436b4e93a897084aceca6b118b8002b20122",
                "org.opencontainers.image.source": "https://github.com/regclient/regclient",
                "org.opencontainers.image.title": "regsync",
                "org.opencontainers.image.url": "https://github.com/regclient/regclient",
                "org.opencontainers.image.vendor": "regclient",
                "org.opencontainers.image.version": "v0.8.2"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 10558231,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a591bbdf23ba3e1e4ea6e756423a2278766afd2bb1e6597c0f544f2709279a08/diff",
                "MergedDir": "/var/lib/docker/overlay2/7007a42633228a30ba3ca0fc86c5e83b1e92d313ca62bd42afb8d85b43263fc8/merged",
                "UpperDir": "/var/lib/docker/overlay2/7007a42633228a30ba3ca0fc86c5e83b1e92d313ca62bd42afb8d85b43263fc8/diff",
                "WorkDir": "/var/lib/docker/overlay2/7007a42633228a30ba3ca0fc86c5e83b1e92d313ca62bd42afb8d85b43263fc8/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:2e2d4a8793ee2e3c285c46d4a08fbc1954eeee3c0a8874d0b8f5900649f0c5db",
                "sha256:ed1ed35a564a4812ad66631737a5ab67ffe7ff48a2f312ec78af6c0ac9a63e47"
            ]
        },
        "Metadata": {
            "LastTagTime": "2025-04-11T17:45:42.646600329+02:00"
        }
    }
]
```

### Environment

I run regsync as a docker container, Platform is SLES 15 SP6 on amd64. When it works it syncs images from GCR and Docker Hub to local containers running registry:latest.

### Anything else

I'm not entirely sure that this is caused by regsync, I more likely have an issue somewhere in the configuration that I can't diagnose deeper because the regsync container image only contains regsync (which is usually a good thing). I already copied the entire stack and switched the regsync container image for busybox with an entrypoint `/bin/sh -c sleep 1d` to get a running container where I can `docker exec -it <containername> /bin/sh` into. After starting this with `docker compose up -d` I can see, that mounting the regsync.yml file works just fine, and it comes with owner root:root and permissions 644, which means the application user `appuser` (uid 1000, gid 1000) is able to read the file... I just hope that you can point me into the right direction here.

**Comment by sudo-bmitch** [comment]
> I more likely have an issue somewhere in the configuration that I can't diagnose deeper because the regsync container image only contains regsync

There's an alpine image with a shell:

```
image: ghcr.io/regclient/regsync:alpine
```

When using the alpine image, the command would need to include "regsync" to run that, but you can also make the command `/bin/sh`, or `tail -f /dev/null` to leave the container running to exec into it and debug.

**Comment by sudo-bmitch** [comment]
In this case, the issue is that `-c` and the filename should be two separate parameters:

```
networks:
  frontend:
    external: true

services:
  regsync:
    image: ghcr.io/regclient/regsync:latest
    command:
      - "-c"
      - "/home/appuser/regsync.yml"
      - "server"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - frontend
    volumes:
      - /etc/pki/trust/anchors/WebProxyCA.crt:/etc/ssl/certs/WebProxyCA.crt:ro
      - ./regsync.yml:/home/appuser/regsync.yml:ro
```
